/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Election;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Nit
 */
public class VotingSystem extends javax.swing.JFrame {

  private List<Candidate> candidateList = new ArrayList<>();
  private List<JCheckBox> checkboxes = new ArrayList<>();
  private Map<String, Integer> voteCounts = new HashMap<>();
  private Set<String> votersWhoHaveVoted = new HashSet<>(); 
    /**
     * Creates new form VotingSystem
     */
    public VotingSystem() {
    initComponents();
      checkboxes.add(chk1);
    checkboxes.add(chk2);
    checkboxes.add(chk3);
    checkboxes.add(chk4);
    checkboxes.add(chk5);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        candidateTable1 = new javax.swing.JTable();
        btnRegister = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        voterTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtSearchVoter = new javax.swing.JTextField();
        btnSearch2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnVote = new javax.swing.JButton();
        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        chk4 = new javax.swing.JCheckBox();
        chk5 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultTable1 = new javax.swing.JTable();
        voteButton1 = new javax.swing.JButton();
        winnerButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Election 2024", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Calligraphy", 1, 36), new java.awt.Color(0, 102, 255))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel1.setText("Register a candidate for the election");

        jLabel2.setText("Enter candidate last name:");

        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter candidate first name");

        candidateTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Last Name", "First Name"
            }
        ));
        jScrollPane1.setViewportView(candidateTable1);

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel4.setText("Search candidates");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegister)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtfname))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(665, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegister)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Candidate", jPanel3);

        jLabel5.setText("Enter NIC");

        txtNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICActionPerformed(evt);
            }
        });

        jLabel6.setText("Enter First Name");

        jLabel7.setText("Enter Last Name");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        voterTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIC", "First Name", "Last Name"
            }
        ));
        jScrollPane2.setViewportView(voterTable2);

        jLabel8.setText("Search Voter");

        btnSearch2.setText("Search");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdd)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtLname))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(txtSearchVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch2)))
                .addContainerGap(611, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSearchVoter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Voters", jPanel4);

        jLabel9.setText("List of the candidates standing for the General Elections:");

        jLabel10.setText("Vote for the 3 candidates only:");

        btnVote.setText("Vote");
        btnVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoteActionPerformed(evt);
            }
        });

        chk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk1ActionPerformed(evt);
            }
        });

        chk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk2ActionPerformed(evt);
            }
        });

        chk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk3ActionPerformed(evt);
            }
        });

        chk4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk4ActionPerformed(evt);
            }
        });

        chk5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(chk1)
                            .addComponent(chk2)
                            .addComponent(chk3)
                            .addComponent(chk4)
                            .addComponent(chk5)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnVote)))
                .addContainerGap(749, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(chk1)
                .addGap(18, 18, 18)
                .addComponent(chk2)
                .addGap(18, 18, 18)
                .addComponent(chk3)
                .addGap(18, 18, 18)
                .addComponent(chk4)
                .addGap(18, 18, 18)
                .addComponent(chk5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnVote)
                .addGap(90, 90, 90))
        );

        jTabbedPane1.addTab("Voting", jPanel5);

        resultTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Votes"
            }
        ));
        jScrollPane3.setViewportView(resultTable1);

        voteButton1.setText("Show votes");
        voteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteButton1ActionPerformed(evt);
            }
        });

        winnerButton1.setText("Show winner");
        winnerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winnerButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(voteButton1)
                        .addGap(18, 18, 18)
                        .addComponent(winnerButton1)))
                .addContainerGap(611, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voteButton1)
                    .addComponent(winnerButton1))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Result", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICActionPerformed

    private void btnVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoteActionPerformed
     String enteredNIC = JOptionPane.showInputDialog(this, "Please enter your NIC:");

        if (enteredNIC == null || enteredNIC.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NIC cannot be empty.");
            return;
        }

        // Validate NIC
        boolean isValidVoter = validateVoterNIC(enteredNIC);
        if (!isValidVoter) {
            JOptionPane.showMessageDialog(this, "Invalid NIC. You must be a registered voter to vote.");
            return;
        }

       
        if (votersWhoHaveVoted.contains(enteredNIC)) {
            JOptionPane.showMessageDialog(this, "You have already voted. You cannot vote twice.");
            return;
        }

        List<String> selectedCandidates = new ArrayList<>();

        for (JCheckBox checkbox : checkboxes) {
            if (checkbox.isSelected()) {
                selectedCandidates.add(checkbox.getText());
            }
        }

        if (selectedCandidates.size() > 3) {
            JOptionPane.showMessageDialog(this, "You can only vote for up to 3 candidates.");
        } else if (selectedCandidates.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select at least one candidate.");
        } else {
            // Update vote counts
            for (String candidateName : selectedCandidates) {
                voteCounts.put(candidateName, voteCounts.getOrDefault(candidateName, 0) + 1);
            }
            
            // Mark this NIC as having voted
            votersWhoHaveVoted.add(enteredNIC);

            JOptionPane.showMessageDialog(this, "Your vote has been recorded.");
        }
    }//GEN-LAST:event_btnVoteActionPerformed


       
    
    private boolean validateVoterNIC(String nic) {
    // Retrieve the table model from voterTable2
    DefaultTableModel model = (DefaultTableModel) voterTable2.getModel();

    // Iterate through each row of the table
    for (int i = 0; i < model.getRowCount(); i++) {
        String tableNIC = (String) model.getValueAt(i, 0); // Assuming NIC is in the first column

        // Check if the entered NIC matches the NIC in the table
        if (nic.equals(tableNIC)) {
            return true; // NIC found in the table
        }
        
    }

    return false; // NIC not found in the table
    }
    
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
   String lastName = txtlname.getText();
    String firstName = txtfname.getText();
    
    if (lastName.isEmpty() || firstName.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in both fields.");
        return;
    }
    
    // Create new candidate and add to the list
    Candidate candidate = new Candidate(lastName, firstName);
    candidateList.add(candidate);

    // Debugging statements
    System.out.println("Candidate added: " + candidate.getFirstName() + " " + candidate.getLastName());

    populateCheckBoxes();
    updateCandidateTable();
    }//GEN-LAST:event_btnRegisterActionPerformed
   
private void updateCandidateTable() {
    // Assuming you have a DefaultTableModel for candidateTable1
    DefaultTableModel model = (DefaultTableModel) candidateTable1.getModel();
    model.setRowCount(0); // Clear existing rows
    
    for (Candidate candidate : candidateList) {
        // Add new rows to the table
        model.addRow(new Object[]{candidate.getFirstName(), candidate.getLastName()});
        
    }
}

    
private void populateCheckBoxes() {
    // Clear existing checkboxes
    chk1.setText("");
    chk2.setText("");
    chk3.setText("");
    chk4.setText("");
    chk5.setText("");
    
    // Ensure there are no more than 6 candidates for checkboxes
    int numCandidates = Math.min(candidateList.size(), 6);

    // Debugging line
    System.out.println("Number of candidates to populate: " + numCandidates);

    for (int i = 0; i < numCandidates; i++) {
        Candidate candidate = candidateList.get(i);
        String candidateName = candidate.getFirstName() + " " + candidate.getLastName();
        
        // Debugging line
        System.out.println("Populating checkbox " + (i+1) + " with name: " + candidateName);

        switch (i) {
            case 0:
                chk1.setText(candidateName);
                break;
            case 1:
                chk2.setText(candidateName);
                break;
            case 2:
                chk3.setText(candidateName);
                break;
            case 3:
                chk4.setText(candidateName);
                break;
            case 4:
                chk5.setText(candidateName);
                break;
            // Optionally handle case 5 if you have more than 5 checkboxes
        }
    }
}

        




    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
          // Retrieve input values
    String nic = txtNIC.getText().trim();
    String firstName = txtFname.getText().trim();
    String lastName = txtLname.getText().trim();
    
    // Basic validation
    if (nic.isEmpty() || firstName.isEmpty() || lastName.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        return;
    }
    
    // Check if NIC already exists in the table
    DefaultTableModel model = (DefaultTableModel) voterTable2.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        if (model.getValueAt(i, 0).equals(nic)) {
            javax.swing.JOptionPane.showMessageDialog(this, "NIC already exists.");
            return;
        }
    }
    
    // Add new row to the table
    model.addRow(new Object[]{nic, firstName, lastName});
    
    // Clear the input fields
    txtNIC.setText("");
    txtFname.setText("");
    txtLname.setText("");
    
    javax.swing.JOptionPane.showMessageDialog(this, "Voter added successfully.");
    }//GEN-LAST:event_btnAddActionPerformed

public class Candidate {
    private String lastName;
    private String firstName;

    public Candidate(String lastName, String firstName) {
        this.lastName = lastName;
        this.firstName = firstName;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    @Override
    public String toString() {
        return "Candidate: " + firstName + " " + lastName;
    }
}
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
                String searchName = txtSearch.getText();
        
        if (searchName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Search field is empty.");
            return;
        }
        
        // Sort candidate list by last name to use binary search
        Collections.sort(candidateList, (c1, c2) -> c1.lastName.compareTo(c2.lastName));
        
        // Perform binary search
        int index = binarySearch(candidateList, searchName, 0, candidateList.size() - 1);
        
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Candidate not found.");
        } else {
            JOptionPane.showMessageDialog(this, "Candidate found: " + candidateList.get(index));
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private int binarySearch(List<Candidate> list, String searchName, int left, int right) {
        if (left > right) {
            return -1; // Not found
        }
        
        int mid = (left + right) / 2;
        Candidate midCandidate = list.get(mid);
        
        if (midCandidate.lastName.equalsIgnoreCase(searchName)) {
            return mid;
        } else if (midCandidate.lastName.compareToIgnoreCase(searchName) < 0) {
            return binarySearch(list, searchName, mid + 1, right);
        } else {
            return binarySearch(list, searchName, left, mid - 1);
        }
    }
    
    private void chk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk1ActionPerformed

    private void chk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk2ActionPerformed

    private void chk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk3ActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
       String searchNIC = txtSearchVoter.getText().trim();
    
    if (searchNIC.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a NIC to search.");
        return;
    }
    
    DefaultTableModel model = (DefaultTableModel) voterTable2.getModel();
    List<String[]> voters = new ArrayList<>();
    
    // Collect the data from the table into a list
    for (int i = 0; i < model.getRowCount(); i++) {
        voters.add(new String[]{
            (String) model.getValueAt(i, 0),
            (String) model.getValueAt(i, 1),
            (String) model.getValueAt(i, 2)
        });
    }
    
    // Sort the list by NIC (to prepare for binary search)
    voters.sort(Comparator.comparing(o -> o[0]));
    
    // Perform binary search
    String[] result = binarySearch2(voters, searchNIC, 0, voters.size() - 1);
    
    if (result != null) {
        // Display found result
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Voter found: \nNIC: " + result[0] + "\nFirst Name: " + result[1] + "\nLast Name: " + result[2]);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Voter not found.");
    }
    }//GEN-LAST:event_btnSearch2ActionPerformed


    
    private void voteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteButton1ActionPerformed
    // Create a map to count votes for each candidate
    voteCounts.clear(); // Clear previous counts

    // Retrieve the table model from the candidateTable1
    DefaultTableModel model = (DefaultTableModel) candidateTable1.getModel();

   
    for (int i = 0; i < model.getRowCount(); i++) {
        String firstName = (String) model.getValueAt(i, 0);
        String lastName = (String) model.getValueAt(i, 1);
        String candidateName = firstName + " " + lastName;

        
        int currentVoteCount = voteCounts.getOrDefault(candidateName, 0);
        int newVoteCount = currentVoteCount + 1; // Increment by 1 or another logic as needed
        voteCounts.put(candidateName, newVoteCount);
    }

    // Update resultTable1 with the vote counts
    updateResultTable();
    
    }//GEN-LAST:event_voteButton1ActionPerformed

    private int getVoteCountForCandidate(String candidateName) {
return voteCounts.getOrDefault(candidateName, 0);
}
    
    private void updateResultTable() {
    // Retrieve the table model from resultTable1
    DefaultTableModel model = (DefaultTableModel) resultTable1.getModel();

    // Clear existing rows
    model.setRowCount(0);

    // Add rows for each candidate and their vote counts
    for (Map.Entry<String, Integer> entry : voteCounts.entrySet()) {
        String[] nameParts = entry.getKey().split(" ", 2);
        String firstName = nameParts[0];
        String lastName = nameParts.length > 1 ? nameParts[1] : "";

        model.addRow(new Object[]{firstName, lastName, entry.getValue()});
    }
}
    
    private void chk4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk4ActionPerformed

    private void chk5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk5ActionPerformed

    private void winnerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winnerButton1ActionPerformed
            if (voteCounts.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No votes have been cast yet.");
        return;
    }

    // Find candidate with the maximum votes
    String winner = null;
    int maxVotes = 0;

    for (Map.Entry<String, Integer> entry : voteCounts.entrySet()) {
        if (entry.getValue() > maxVotes) {
            maxVotes = entry.getValue();
            winner = entry.getKey();
        }
    }

    if (winner != null) {
        JOptionPane.showMessageDialog(this, "The winner is: " + winner + " with " + maxVotes + " votes.");
    } else {
        JOptionPane.showMessageDialog(this, "No winner could be determined.");
    }
    }//GEN-LAST:event_winnerButton1ActionPerformed
    



    
    private String[] binarySearch2(List<String[]> sortedList2, String targetNIC, int left, int right) {
    if (left > right) {
        return null; // Base case: target not found
    }
    
    int mid = left + (right - left) / 2;
    String[] midValue = sortedList2.get(mid);
    
    if (midValue[0].equals(targetNIC)) {
        return midValue; // Found the target NIC
    }
    
    if (targetNIC.compareTo(midValue[0]) < 0) {
        return binarySearch2(sortedList2, targetNIC, left, mid - 1); // Search in the left half
    } else {
        return binarySearch2(sortedList2, targetNIC, mid + 1, right); // Search in the right half
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VotingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      //</editor-fold>
      
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VotingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JButton btnVote;
    private javax.swing.JTable candidateTable1;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JCheckBox chk4;
    private javax.swing.JCheckBox chk5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable resultTable1;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchVoter;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JButton voteButton1;
    private javax.swing.JTable voterTable2;
    private javax.swing.JButton winnerButton1;
    // End of variables declaration//GEN-END:variables
}
